add eks deployment code

diff --git a/.github/workflows/eks-deploy.yml b/.github/workflows/eks-deploy.yml
--- a/.github/workflows/eks-deploy.yml
+++ b/.github/workflows/eks-deploy.yml
@@ -39,14 +39,45 @@ jobs:
       
 
         
-      # - name: Push Images to ECR
-      #   run: |
+      - name: Push Images to ECR
+        run: |
 
-      #     # Login to ECR
-      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username ${{ secrets.AWS_USERNAME }} --password-stdin ${{ secrets.ECR_REGISTRY }}
+          # Login to ECR
+          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username ${{ secrets.AWS_USERNAME }} --password-stdin ${{ secrets.ECR_REGISTRY }}
 
-      #     # Push to ECR
-      #     docker push ${{ secrets.ECR_REPO }}:$GITHUB_SHA
+          # Push to ECR
+          docker push ${{ secrets.CFGOV_IMAGE }}:$GITHUB_SHA
+          docker push ${{ secrets.CFGOV_APACHE_IMAGE }}:$GITHUB_SHA
 
-      # - name: Say Hello World
-      #   run: echo "Hello World"
+      - name: Install K8s/Helm
+        run: |
+
+          # Install Helm
+          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
+          chmod 700 get_helm.sh
+          ./get_helm.sh
+
+          # Install kubectl
+          curl -o ./kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.25.14/2023-10-17/bin/linux/amd64/kubectl
+          curl -o ./kubectl.sha256 https://s3.us-west-2.amazonaws.com/amazon-eks/1.25.14/2023-10-17/bin/linux/amd64/kubectl.sha256
+          (diff  <(openssl sha256 kubectl | awk {'print $2'}) <(cat kubectl.sha256 | awk {'print $1'}) &&
+            echo 'kubectl checksum matches, enabling usage') || (echo 'kubectl checksum failed, exiting' && exit 1)
+          chmod +x kubectl
+          mkdir -p $HOME/bin && mv kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
+          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
+          source ~/.bashrc
+          kubectl version --client
+
+          # Update kubeconfig to point to EKS Cluster
+          aws eks update-kubeconfig --name $CLUSTER_NAME --region us-east-1
+      
+      - name: Deploy to EKS
+        run: >
+          helm upgrade --install cfgov ./helm --values ./helm/values.eks.yaml 
+          --set initContainers[1].image.repository=${{ secrets.CFGOV_IMAGE }}
+          --set initContainer[1].image.tag=${GITHUB_SHA}
+          --set containers[0].image.repository=${{ secrets.CFGOV_IMAGE }}
+          --set containers[0].image.tag=${GITHUB_SHA}
+          --set containers[1].image.repository=${{ secrets.CFGOV_APACHE_IMAGE }}
+          --set containers[1].image.tag=${GITHUB_SHA}
+          --set mapping.host=${{ secrets.HOST }}
